name: curso_react
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
    - Flask
    - Flask-CORS
    - gunicorn
    - flask-sqlalchemy
    - psycopg2-binary
    - flask-migrate
    - flask-jwt-extended 
